package com.ledgerguard.detection.explain.llm;

import com.ledgerguard.detection.explain.AccountExplanation;
import com.ledgerguard.detection.explain.Reconciliation;
import com.ledgerguard.detection.explain.SignalContribution;
import com.ledgerguard.detection.explain.StatisticalExplanation;
import com.ledgerguard.detection.ml.FeatureAttribution;
import com.ledgerguard.detection.ml.MlExplanation;

import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Everything the model is allowed to know about one account.
 *
 * <h2>The closed world</h2>
 *
 * This record is the model's entire universe. It is built from
 * {@link AccountExplanation} and from nothing else — no second pass over the
 * ledger, no extra query, no recomputation — so a fact the model states either
 * appears here or was invented. That is what makes the validator in
 * {@link NarrativeValidator} possible at all: grounding is only checkable
 * against a payload that is known to be complete.
 *
 * <h2>No user-controlled text reaches the model</h2>
 *
 * Worth stating explicitly because it is a security property rather than an
 * accident. The payload carries enum names, numbers, and sentences generated by
 * Phase 8's own signal code. It carries no payment descriptions, no counterparty
 * names, no account labels — the detection layer never collected any of them.
 * The prompt-injection surface is therefore a set of doubles and a fixed
 * vocabulary of identifiers, which is about as small as it gets for a system
 * that sends anything to a model at all.
 *
 * <h2>Rounded on the way in</h2>
 *
 * Scores, shares and percentiles are rounded here rather than at the point of
 * rendering. Three reasons, all of them about keeping one number in one form:
 * the model sees the same digits the validator will accept, the cache key is
 * stable against floating-point noise far below anything a sentence would
 * mention, and prose quoting "0.5558333" reads like a machine talking to itself.
 */
public record NarrativeEvidence(
        Statistical statistical,
        Model model,
        String agreement,
        boolean corroborated,
        List<String> corroboratedSignals,
        List<String> driversOutsideStatisticalView) {

    /** Three decimals: finer than any sentence needs, coarser than float noise. */
    private static final int SCALE = 1000;

    /** How many model drivers the narrative is offered. Beyond three is noise. */
    private static final int DRIVERS = 3;

    public record Statistical(
            double composite,
            int applicableSignals,
            boolean wellEvidenced,
            List<Signal> signals) {
    }

    /**
     * @param detail the signal's own sentence, from the Phase 8 code that did
     *               the arithmetic. Passed verbatim: it is the richest grounded
     *               material in the payload, and paraphrasing it here would put
     *               a third wording of one fact into the system
     */
    public record Signal(
            String name,
            boolean applicable,
            boolean fired,
            double score,
            double contribution,
            String detail) {
    }

    /** Null when no forest has been trained; the narrative then has one layer to describe. */
    public record Model(
            double score,
            int trainingRows,
            List<Driver> drivers) {
    }

    public record Driver(
            String feature,
            double share,
            double percentile,
            String direction) {
    }

    public static NarrativeEvidence of(AccountExplanation explanation) {
        StatisticalExplanation statistical = explanation.statistical();

        List<Signal> signals = statistical.contributions().stream()
                .map(NarrativeEvidence::signal)
                .toList();

        Model model = null;
        if (explanation.hasModel()) {
            MlExplanation ml = explanation.ml();
            model = new Model(
                    round(ml.score()),
                    ml.trainingRows(),
                    ml.topDrivers(DRIVERS).stream().map(NarrativeEvidence::driver).toList());
        }

        Reconciliation reconciliation = explanation.reconciliation();

        return new NarrativeEvidence(
                new Statistical(
                        round(statistical.composite()),
                        statistical.applicableSignals(),
                        statistical.wellEvidenced(),
                        signals),
                model,
                reconciliation == null ? null : reconciliation.agreement().name(),
                reconciliation != null && reconciliation.corroborated(),
                reconciliation == null ? List.of() : reconciliation.corroboratedSignals(),
                reconciliation == null ? List.of() : reconciliation.modelDriversOutsideView());
    }

    private static Signal signal(SignalContribution contribution) {
        return new Signal(
                contribution.signal(),
                contribution.applicable(),
                contribution.fired(),
                round(contribution.score()),
                round(contribution.contribution()),
                contribution.explanation());
    }

    private static Driver driver(FeatureAttribution attribution) {
        return new Driver(
                attribution.feature(),
                round(attribution.share()),
                round(attribution.percentile()),
                attribution.direction());
    }

    private static double round(double value) {
        return Math.round(value * SCALE) / (double) SCALE;
    }

    public boolean hasModel() {
        return model != null;
    }

    /**
     * Every identifier the narrative is permitted to name.
     *
     * <p>Signal names and feature names only. A narrative mentioning an
     * identifier outside this set has either renamed something it was given or
     * invented something it was not, and the validator treats both the same way
     * because from the reader's side they are the same failure.
     */
    public Set<String> mentionableIdentifiers() {
        Set<String> identifiers = new LinkedHashSet<>();
        statistical.signals().forEach(signal -> identifiers.add(signal.name()));
        if (model != null) {
            model.drivers().forEach(driver -> identifiers.add(driver.feature()));
        }
        identifiers.addAll(driversOutsideStatisticalView);
        identifiers.addAll(corroboratedSignals);
        return identifiers;
    }

    /**
     * Every number the narrative is permitted to state.
     *
     * <p>Includes the numbers embedded in each signal's own sentence — they are
     * evidence, and a narrative quoting "90000.00 USD" from the amount signal's
     * detail is doing exactly what it was asked to do. The validator widens each
     * of these into its truthful renderings rather than demanding an exact
     * string match; see {@link NarrativeValidator}.
     */
    public List<Double> mentionableNumbers() {
        List<Double> numbers = new ArrayList<>();
        numbers.add(statistical.composite());
        numbers.add((double) statistical.applicableSignals());

        for (Signal signal : statistical.signals()) {
            numbers.add(signal.score());
            numbers.add(signal.contribution());
            numbers.addAll(NumericGrounding.valuesIn(signal.detail()));
        }

        if (model != null) {
            numbers.add(model.score());
            numbers.add((double) model.trainingRows());
            for (Driver driver : model.drivers()) {
                numbers.add(driver.share());
                numbers.add(driver.percentile());
            }
        }
        return numbers;
    }
}
