package com.ledgerguard.detection.explain.llm;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.ledgerguard.detection.explain.ForbiddenVocabulary;

/**
 * The prompt, and the canonical form of the evidence it carries.
 *
 * <h2>The framing: rewriting, not analysing</h2>
 *
 * The single most important line in the system message is the one that tells
 * the model what job it has. Asked to "explain why this account is anomalous",
 * a model will reason — it will weigh, infer motive, and reach for the word
 * "likely". Asked to "rewrite this record as prose, adding nothing", the same
 * model does something much closer to what is wanted, because the second
 * framing has no room for a conclusion the record does not contain.
 *
 * <p>Everything else is scaffolding around that sentence: the rules are stated
 * as prohibitions, the forbidden vocabulary is given rather than merely
 * enforced, and the worked example shows an evidence payload <em>next to</em>
 * its narrative so the model can see that every number in the output came from
 * the input. Showing the output alone would have taught the style and not the
 * constraint.
 *
 * <h2>Belt and braces, deliberately</h2>
 *
 * Every rule here is also checked after generation by
 * {@link NarrativeValidator}. That is not redundancy to be tidied away: a
 * prompt is a request and a validator is a guarantee, and the difference
 * matters precisely on the inputs where a model is most likely to improvise.
 * The prompt exists to make rejection rare; the validator exists to make it
 * safe when the prompt fails.
 *
 * <h2>Versioning</h2>
 *
 * {@link #PROMPT_VERSION} is part of the cache key. Editing the wording of this
 * class without bumping it would serve prose generated by the old prompt as if
 * the new one had produced it.
 */
public final class PromptBuilder {

    /** Bump on any change to the system message or the evidence shape. */
    public static final String PROMPT_VERSION = "p11-v1";

    private static final ObjectMapper JSON = new ObjectMapper();

    private PromptBuilder() {
    }

    public static String systemPrompt() {
        return """
                You rewrite a fixed evidence record about one financial account into a short \
                plain-text summary for a human reviewer. You are a renderer, not an analyst. \
                The record is complete: it contains everything that is known, and everything \
                you are permitted to say.

                HARD RULES
                1. State no fact that is not in the record. No inference, no extrapolation, \
                no background knowledge about finance or fraud.
                2. Every number you write must appear in the record. Do not compute new \
                numbers, do not convert between scales, do not round to fewer than the digits \
                shown where that changes the value.
                3. Name only signals and features that appear in the record, spelled exactly \
                as the record spells them.
                4. Never claim wrongdoing, intent, risk, or certainty. These scores are not \
                validated against any known outcome. Describe only how the account's behaviour \
                departs from a named reference: its own history, or the population the model \
                was trained on.
                5. Never use any of these words: %s
                6. Never recommend an action, an investigation, or a decision.
                7. If the record says a signal could not judge, say it could not judge. Do not \
                describe it as quiet, clean, or normal.

                STYLE
                Three to five sentences. Plain text only: no markdown, no headings, no bullet \
                points, no preamble such as "Here is a summary". Begin with the statistical \
                layer, then the model, then how the two relate. Write for a reviewer who knows \
                the system and wants the shape of the evidence quickly.

                WORKED EXAMPLE
                Record:
                %s
                Acceptable narrative:
                %s

                Note that every number and every name in that narrative appears in that \
                record. Yours must do the same, against your own record. The example's values \
                are not yours; never carry them over.
                """
                .formatted(ForbiddenVocabulary.asPromptList(), EXAMPLE_RECORD, EXAMPLE_NARRATIVE);
    }

    public static String userPrompt(NarrativeEvidence evidence) {
        return """
                Record:
                %s

                Write the narrative now. Plain text only.
                """.formatted(toJson(evidence));
    }

    /**
     * The evidence as one deterministic JSON string.
     *
     * <p>Deterministic because it is the cache key as well as the prompt: record
     * components serialise in declaration order, and every double was rounded to
     * three decimals when the evidence was built, so the same account with the
     * same numbers produces byte-identical text.
     */
    public static String toJson(NarrativeEvidence evidence) {
        try {
            return JSON.writeValueAsString(evidence);
        } catch (JsonProcessingException e) {
            // The evidence is a record of primitives, strings and lists of the
            // same. If this throws, something is structurally wrong rather than
            // transiently broken, and silently narrating a partial record would
            // be worse than falling back to the template.
            throw new IllegalStateException("evidence could not be serialised for the prompt", e);
        }
    }

    /**
     * A deliberately different account from anything the tests or the ledger
     * produce, so that a value bleeding out of the example into a real narrative
     * is caught by numeric grounding rather than blending in.
     */
    private static final String EXAMPLE_RECORD = """
            {"statistical":{"composite":0.41,"applicableSignals":3,"wellEvidenced":true,\
            "signals":[{"name":"velocity","applicable":true,"fired":true,"score":0.82,\
            "contribution":0.41,"detail":"37 payments in the last 1h against an expected 2.10"},\
            {"name":"burst","applicable":false,"fired":false,"score":0.0,"contribution":0.0,\
            "detail":"insufficient data: 2 payments in the recent window; a cluster needs at least 3"}]},\
            "model":{"score":0.44,"trainingRows":180,"drivers":[]},\
            "agreement":"STATISTICAL_ONLY","corroborated":false,\
            "corroboratedSignals":[],"driversOutsideStatisticalView":[]}""";

    private static final String EXAMPLE_NARRATIVE = """
            The statistical composite is 0.41 over 3 applicable signals, driven by velocity at \
            0.41 of the composite: 37 payments in the last hour against an expected 2.10. The \
            burst signal could not judge, having only 2 payments in the recent window where a \
            cluster needs 3. The model scores 0.44 against 180 training accounts and isolated \
            this account on no feature in particular. The two layers therefore point in \
            different directions, with the departure visible against this account's own rate \
            and not against the training population.""";
}
