import type { AccountLabel } from '../../api/types';
import { instant, latency } from './format';

/**
 * A verdict, and everything that determines what the verdict is worth.
 *
 * <h2>Why the whole label is the prop</h2>
 *
 * The component takes an `AccountLabel`, never a verdict string. A chip that
 * accepted `verdict="ANOMALOUS"` could be rendered without provenance, and
 * "confirmed anomalous" with no source attached is the exact failure Phase 12
 * built three enums to prevent: a human reviewer's judgement, a card scheme's
 * chargeback and an account this system generated to be anomalous are three
 * different epistemic objects wearing the same word.
 *
 * Taking the whole record makes the provenance structurally inseparable from the
 * verdict. There is no code path through this file that renders one without the
 * other, and a test pins that.
 *
 * <h2>The four things that qualify a verdict</h2>
 *
 * <ul>
 *   <li><b>Source</b> — what kind of evidence this is. SYNTHETIC gets a standing
 *       warning, because it is the only source that can be produced in volume on
 *       demand and therefore the only one that can fill a screen with confident
 *       labels that measure nothing about the real world.</li>
 *   <li><b>Stratum</b> — which pool the account was drawn from. FLAGGED is dense
 *       in positives and biased; AUDIT is the only honest recall denominator.</li>
 *   <li><b>Scores visible</b> — an anchored verdict is partly an opinion about
 *       the detector's opinion, and cannot be read as independent.</li>
 *   <li><b>Latency</b> — the gap between the behaviour and the truth about it.</li>
 * </ul>
 */
export function LabelChip({ label }: { label: AccountLabel }) {
  const synthetic = label.source === 'SYNTHETIC';

  return (
    <div
      className={`label-chip${synthetic ? ' synthetic' : ''}`}
      data-verdict={label.verdict}
      data-source={label.source}
      data-stratum={label.stratum}
    >
      <span className="label-verdict">
        Judged {label.verdict.toLowerCase()}
        {label.verdict === 'UNCLEAR' ? ' — looked at, and not judgeable from what was available' : ''}
      </span>

      <span className="label-provenance">
        Source: {sourceWording(label.source)} · Stratum: {stratumWording(label.stratum)}
      </span>

      <span className="label-meta">
        {label.scoresVisible
          ? 'Reviewer could see the detector’s scores — anchored, not independent'
          : 'Reviewer judged blind to the detector’s scores'}
        {' · '}
        {latency(label.latencySeconds)} after the behaviour
        {' · '}
        {label.reviewer}
        {' · '}
        {instant(label.labelledAsOf)}
      </span>

      {synthetic && (
        <p className="label-warning">
          Generated by this system with known ground truth. Useful for exercising the harness;
          circular as evidence about detection quality, and never pooled with the other two sources.
        </p>
      )}

      {label.notes && <span className="label-meta">Notes: {label.notes}</span>}
    </div>
  );
}

/** No label is not a verdict of benign, and the copy has to say so out loud. */
export function NoLabel() {
  return (
    <span className="label-none">
      No label recorded. Nobody has judged this account and no dispute has arrived — which is an
      absence of evidence, not a verdict of ordinary.
    </span>
  );
}

function sourceWording(source: AccountLabel['source']): string {
  switch (source) {
    case 'HUMAN_REVIEW':
      return 'human review';
    case 'DISPUTE_FEED':
      return 'dispute feed (independent of this system)';
    case 'SYNTHETIC':
      return 'synthetic (generated by this system)';
  }
}

function stratumWording(stratum: AccountLabel['stratum']): string {
  return stratum === 'FLAGGED'
    ? 'flagged pool (dense in positives, biased)'
    : 'audit pool (random sample of unflagged accounts)';
}

/**
 * The compact form for the ranking, which still cannot drop provenance.
 *
 * Shorter, not looser: source and stratum are abbreviated but present. A column
 * that showed only "anomalous" would let a synthetic label and a chargeback sort
 * as the same thing.
 */
export function LabelSummary({ labels }: { labels: AccountLabel[] }) {
  if (labels.length === 0) {
    return <span className="label-none">not labelled</span>;
  }

  const newest = labels.reduce((latest, candidate) =>
    candidate.observedAt > latest.observedAt ? candidate : latest,
  );

  return (
    <span data-verdict={newest.verdict} data-source={newest.source} data-stratum={newest.stratum}>
      <span className="label-verdict">{newest.verdict.toLowerCase()}</span>
      <br />
      <span className="label-meta">
        {shortSource(newest.source)} · {newest.stratum.toLowerCase()} pool
        {newest.scoresVisible ? ' · anchored' : ' · blind'}
        {labels.length > 1 ? ` · ${labels.length} labels` : ''}
      </span>
    </span>
  );
}

function shortSource(source: AccountLabel['source']): string {
  switch (source) {
    case 'HUMAN_REVIEW':
      return 'human review';
    case 'DISPUTE_FEED':
      return 'dispute feed';
    case 'SYNTHETIC':
      return 'synthetic';
  }
}
