package com.ledgerguard.validation;

/**
 * Where a label came from, and therefore what it is worth.
 *
 * <h2>Never pool these by accident</h2>
 *
 * They are three different epistemic objects wearing the same shape. A human
 * reviewer's judgement, a card scheme's chargeback, and an account this system
 * generated to be anomalous are not interchangeable evidence, and a metric that
 * silently mixes them is not measuring anything anyone can name.
 *
 * <p>The dangerous one is {@link #SYNTHETIC}. It is the only source that can be
 * produced in volume on demand, which makes it the only one that can single-
 * handedly fill a report with confident numbers — numbers that measure whether
 * a detector finds anomalies designed by someone who knew what the detector
 * looks for. Every evaluation names its sources, and the synthetic benchmark is
 * reported separately and never added to the others.
 */
public enum LabelSource {

    /**
     * A person looked at the account and judged it. The most expensive source,
     * the only one available for accounts nothing external ever disputed, and
     * the only one whose sampling this system controls.
     */
    HUMAN_REVIEW,

    /**
     * A card scheme or bank disputed a payment as fraudulent. Independent of
     * this system by construction, which is its whole value — and incomplete,
     * late, and biased toward fraud that someone eventually noticed.
     */
    DISPUTE_FEED,

    /**
     * Generated by this system with known ground truth. Useful for exercising
     * the harness and for sanity checks; circular as evidence about detection
     * quality. See VALIDATION_REPORT.md.
     */
    SYNTHETIC;

    /** Whether a figure derived from this source may be described as validation. */
    public boolean isEvidenceAboutTheRealWorld() {
        return this != SYNTHETIC;
    }
}
